# Site settings
title: noamelf.com
header-img: img/home-bg.jpg
email: noamelf@gmail.com
copyright_name: Noam Elfanbaum
description: "Thoughts and writing by Noam Elfanbaum"
baseurl: ""
url: "http://noamelf.github.io"
twitter_username: noamelf
github_username: noamelf
facebook_username:  noamelf
email_username:  noamelf@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
