# Site settings
title: noamelf
header-img: img/home2.jpg
email: noamelf@gmail.com
copyright_name: Noam Elfanbaum
description: "Thoughts and writings by Noam Elfanbaum"
baseurl: ""
url: "http://noamelf.github.io"
twitter_username: noamelf
github_username: noamelf
facebook_username:  noamelf
email_username:  noamelf@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-62273869-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
